//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlant_Project.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_in_Group
    {
        public int clients_group_id { get; set; }
        public int Client_id { get; set; }
        public int Group_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Groups Groups { get; set; }
    }
}
