//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlant_Project.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int schedule_id { get; set; }
        public System.DateTime Day { get; set; }
        public int Start_Time_id { get; set; }
        public int End_Time_id { get; set; }
        public int Room_id { get; set; }
        public int Group_id { get; set; }
        public int Section_id { get; set; }
        public int Trainer_id { get; set; }
    
        public virtual Instructor Instructor { get; set; }
        public virtual Rooms Rooms { get; set; }
        public virtual Sections Sections { get; set; }
        public virtual Time Time { get; set; }
        public virtual Time Time1 { get; set; }
    }
}
